### PR TITLE
Fix circular transpilation

### LINKED ISSUE #25: Circular introscope exporting for non-Jest environments
With `"enable": true` all the imports of a file will lead to transpiling it, which makes it impossible to test second level modules (those which import functions from others with introscope enabled).

### PR DESCRIPTION
**Pull request by peter-leonov**
Fixes #25.

This is a dirty workaround, but I have no time now to make it proper.

The proper solution, btw, would be to make Jest understand query params
in imports https://github.com/facebook/jest/pull/6282

### CODE REVIEW

**Comment by peter-leonov** [comment]
:

**Comment by peter-leonov** [comment]
👍

File: babel-plugin.js [hunk 1]
```diff
@@ -457,9 +472,6 @@ function processProgram({ types: t }, programPath, programOpts) {
     };
 
     function test(path, statepath) {
-        if (!options.enable) {
-            return false;
-        }
```
Comment (peter-leonov) [inline babel-plugin.js]: This one worked.

File: babel-plugin.js [hunk 2]
```diff
@@ -88,7 +88,15 @@ const STANDARD_BUILTINS = [
     '_asyncToGenerator',
 ];
 
+let hackyCount = undefined
```
Comment (peter-leonov) [inline babel-plugin.js]: This crap did not work for now.

**Comment by undrafted** [comment]
👍

File: babel-plugin.js [hunk 3]
```diff
@@ -104,6 +112,8 @@ const mergeIntoOptions = (options, opts) => {
     Object.assign(options, opts);
 };
 
+let howDeepIsYourLove = 0
```
Comment (undrafted) [inline babel-plugin.js:115]: lol ❤️
